import { Player, Team, Match } from './types';

// 2024-25 Premier League season — top London clubs + Liverpool
export const mockTeams: Team[] = [
  {
    id: 'team-ars',
    name: 'Arsenal FC',
    shortName: 'Arsenal',
    logo: 'https://crests.football-data.org/57.svg',
    country: 'England',
    founded: 1886,
    stadium: 'Emirates Stadium',
    wins: 26,
    losses: 7,
    draws: 5,
    goalsDifference: 43,
  },
  {
    id: 'team-che',
    name: 'Chelsea FC',
    shortName: 'Chelsea',
    logo: 'https://crests.football-data.org/61.svg',
    country: 'England',
    founded: 1905,
    stadium: 'Stamford Bridge',
    wins: 18,
    losses: 12,
    draws: 8,
    goalsDifference: 20,
  },
  {
    id: 'team-thfc',
    name: 'Tottenham Hotspur',
    shortName: 'Spurs',
    logo: 'https://crests.football-data.org/73.svg',
    country: 'England',
    founded: 1882,
    stadium: 'Tottenham Hotspur Stadium',
    wins: 14,
    losses: 17,
    draws: 7,
    goalsDifference: -3,
  },
  {
    id: 'team-lfc',
    name: 'Liverpool FC',
    shortName: 'Liverpool',
    logo: 'https://crests.football-data.org/64.svg',
    country: 'England',
    founded: 1892,
    stadium: 'Anfield',
    wins: 28,
    losses: 5,
    draws: 5,
    goalsDifference: 52,
  },
];

export const mockPlayers: Player[] = [
  // ── Arsenal ──────────────────────────────────────────────────────────
  {
    id: 'player-a1',
    name: 'David Raya',
    position: 'GK',
    teamId: 'team-ars',
    nationality: 'Spain',
    goals: 0,
    assists: 0,
    matches: 28,
    jerseyNumber: 22,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: 'player-a2',
    name: 'William Saliba',
    position: 'DEF',
    teamId: 'team-ars',
    nationality: 'France',
    goals: 2,
    assists: 1,
    matches: 28,
    jerseyNumber: 12,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: 'player-a3',
    name: 'Ben White',
    position: 'DEF',
    teamId: 'team-ars',
    nationality: 'England',
    goals: 0,
    assists: 3,
    matches: 22,
    jerseyNumber: 4,
    yellowCards: 2,
    redCards: 0,
  },
  {
    id: 'player-a4',
    name: 'Declan Rice',
    position: 'MID',
    teamId: 'team-ars',
    nationality: 'England',
    goals: 7,
    assists: 8,
    matches: 29,
    jerseyNumber: 41,
    yellowCards: 8,
    redCards: 1,
  },
  {
    id: 'player-a5',
    name: 'Martin Ødegaard',
    position: 'MID',
    teamId: 'team-ars',
    nationality: 'Norway',
    goals: 5,
    assists: 7,
    matches: 20,
    jerseyNumber: 8,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: 'player-a6',
    name: 'Bukayo Saka',
    position: 'FWD',
    teamId: 'team-ars',
    nationality: 'England',
    goals: 14,
    assists: 11,
    matches: 29,
    jerseyNumber: 7,
    yellowCards: 2,
    redCards: 0,
  },
  {
    id: 'player-a7',
    name: 'Gabriel Martinelli',
    position: 'FWD',
    teamId: 'team-ars',
    nationality: 'Brazil',
    goals: 9,
    assists: 5,
    matches: 27,
    jerseyNumber: 11,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: 'player-a8',
    name: 'Gabriel Jesus',
    position: 'FWD',
    teamId: 'team-ars',
    nationality: 'Brazil',
    goals: 5,
    assists: 3,
    matches: 15,
    jerseyNumber: 9,
    yellowCards: 2,
    redCards: 0,
  },

  // ── Chelsea ───────────────────────────────────────────────────────────
  {
    id: 'player-c1',
    name: 'Robert Sánchez',
    position: 'GK',
    teamId: 'team-che',
    nationality: 'Spain',
    goals: 0,
    assists: 0,
    matches: 26,
    jerseyNumber: 1,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: 'player-c2',
    name: 'Levi Colwill',
    position: 'DEF',
    teamId: 'team-che',
    nationality: 'England',
    goals: 1,
    assists: 2,
    matches: 28,
    jerseyNumber: 26,
    yellowCards: 4,
    redCards: 0,
  },
  {
    id: 'player-c3',
    name: 'Marc Cucurella',
    position: 'DEF',
    teamId: 'team-che',
    nationality: 'Spain',
    goals: 0,
    assists: 4,
    matches: 30,
    jerseyNumber: 3,
    yellowCards: 6,
    redCards: 0,
  },
  {
    id: 'player-c4',
    name: 'Moisés Caicedo',
    position: 'MID',
    teamId: 'team-che',
    nationality: 'Ecuador',
    goals: 2,
    assists: 3,
    matches: 29,
    jerseyNumber: 25,
    yellowCards: 9,
    redCards: 1,
  },
  {
    id: 'player-c5',
    name: 'Cole Palmer',
    position: 'MID',
    teamId: 'team-che',
    nationality: 'England',
    goals: 22,
    assists: 11,
    matches: 32,
    jerseyNumber: 20,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: 'player-c6',
    name: 'Enzo Fernández',
    position: 'MID',
    teamId: 'team-che',
    nationality: 'Argentina',
    goals: 3,
    assists: 6,
    matches: 25,
    jerseyNumber: 8,
    yellowCards: 7,
    redCards: 0,
  },
  {
    id: 'player-c7',
    name: 'Nicolas Jackson',
    position: 'FWD',
    teamId: 'team-che',
    nationality: 'Senegal',
    goals: 17,
    assists: 5,
    matches: 30,
    jerseyNumber: 15,
    yellowCards: 6,
    redCards: 1,
  },
  {
    id: 'player-c8',
    name: 'Noni Madueke',
    position: 'FWD',
    teamId: 'team-che',
    nationality: 'England',
    goals: 8,
    assists: 4,
    matches: 24,
    jerseyNumber: 31,
    yellowCards: 2,
    redCards: 0,
  },

  // ── Tottenham Hotspur ─────────────────────────────────────────────────
  {
    id: 'player-t1',
    name: 'Guglielmo Vicario',
    position: 'GK',
    teamId: 'team-thfc',
    nationality: 'Italy',
    goals: 0,
    assists: 0,
    matches: 28,
    jerseyNumber: 13,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: 'player-t2',
    name: 'Cristian Romero',
    position: 'DEF',
    teamId: 'team-thfc',
    nationality: 'Argentina',
    goals: 3,
    assists: 1,
    matches: 24,
    jerseyNumber: 17,
    yellowCards: 8,
    redCards: 2,
  },
  {
    id: 'player-t3',
    name: 'Micky van de Ven',
    position: 'DEF',
    teamId: 'team-thfc',
    nationality: 'Netherlands',
    goals: 1,
    assists: 2,
    matches: 20,
    jerseyNumber: 37,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: 'player-t4',
    name: 'Pedro Porro',
    position: 'DEF',
    teamId: 'team-thfc',
    nationality: 'Spain',
    goals: 4,
    assists: 7,
    matches: 28,
    jerseyNumber: 23,
    yellowCards: 4,
    redCards: 0,
  },
  {
    id: 'player-t5',
    name: 'Yves Bissouma',
    position: 'MID',
    teamId: 'team-thfc',
    nationality: 'Mali',
    goals: 1,
    assists: 2,
    matches: 25,
    jerseyNumber: 29,
    yellowCards: 8,
    redCards: 1,
  },
  {
    id: 'player-t6',
    name: 'Dejan Kulusevski',
    position: 'MID',
    teamId: 'team-thfc',
    nationality: 'Sweden',
    goals: 8,
    assists: 12,
    matches: 29,
    jerseyNumber: 21,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: 'player-t7',
    name: 'Son Heung-min',
    position: 'FWD',
    teamId: 'team-thfc',
    nationality: 'South Korea',
    goals: 17,
    assists: 8,
    matches: 30,
    jerseyNumber: 7,
    yellowCards: 2,
    redCards: 0,
  },
  {
    id: 'player-t8',
    name: 'Dominic Solanke',
    position: 'FWD',
    teamId: 'team-thfc',
    nationality: 'England',
    goals: 9,
    assists: 4,
    matches: 31,
    jerseyNumber: 9,
    yellowCards: 4,
    redCards: 0,
  },

  // ── Liverpool ─────────────────────────────────────────────────────────
  {
    id: 'player-l1',
    name: 'Alisson Becker',
    position: 'GK',
    teamId: 'team-lfc',
    nationality: 'Brazil',
    goals: 0,
    assists: 0,
    matches: 28,
    jerseyNumber: 1,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: 'player-l2',
    name: 'Virgil van Dijk',
    position: 'DEF',
    teamId: 'team-lfc',
    nationality: 'Netherlands',
    goals: 3,
    assists: 2,
    matches: 29,
    jerseyNumber: 4,
    yellowCards: 2,
    redCards: 0,
  },
  {
    id: 'player-l3',
    name: 'Trent Alexander-Arnold',
    position: 'DEF',
    teamId: 'team-lfc',
    nationality: 'England',
    goals: 4,
    assists: 12,
    matches: 28,
    jerseyNumber: 66,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: 'player-l4',
    name: 'Alexis Mac Allister',
    position: 'MID',
    teamId: 'team-lfc',
    nationality: 'Argentina',
    goals: 5,
    assists: 7,
    matches: 28,
    jerseyNumber: 10,
    yellowCards: 6,
    redCards: 0,
  },
  {
    id: 'player-l5',
    name: 'Dominik Szoboszlai',
    position: 'MID',
    teamId: 'team-lfc',
    nationality: 'Hungary',
    goals: 6,
    assists: 5,
    matches: 27,
    jerseyNumber: 8,
    yellowCards: 5,
    redCards: 0,
  },
  {
    id: 'player-l6',
    name: 'Mohamed Salah',
    position: 'FWD',
    teamId: 'team-lfc',
    nationality: 'Egypt',
    goals: 28,
    assists: 17,
    matches: 31,
    jerseyNumber: 11,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: 'player-l7',
    name: 'Luis Díaz',
    position: 'FWD',
    teamId: 'team-lfc',
    nationality: 'Colombia',
    goals: 15,
    assists: 7,
    matches: 28,
    jerseyNumber: 7,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: 'player-l8',
    name: 'Cody Gakpo',
    position: 'FWD',
    teamId: 'team-lfc',
    nationality: 'Netherlands',
    goals: 12,
    assists: 5,
    matches: 26,
    jerseyNumber: 18,
    yellowCards: 2,
    redCards: 0,
  },
];

export const mockMatches: Match[] = [
  // ── Match 1: Arsenal 2-1 Chelsea (completed) ──────────────────────────
  {
    id: 'match-1',
    homeTeamId: 'team-ars',
    awayTeamId: 'team-che',
    date: '2025-01-14T20:00:00.000Z',
    status: 'completed',
    homeScore: 2,
    awayScore: 1,
    events: [
      { id: 'e1-1', type: 'goal',        minute: 18, playerId: 'player-a6', teamId: 'team-ars' }, // Saka
      { id: 'e1-2', type: 'yellow_card', minute: 34, playerId: 'player-c4', teamId: 'team-che' }, // Caicedo
      { id: 'e1-3', type: 'goal',        minute: 47, playerId: 'player-c7', teamId: 'team-che' }, // Jackson
      { id: 'e1-4', type: 'goal',        minute: 63, playerId: 'player-a5', teamId: 'team-ars' }, // Ødegaard
      { id: 'e1-5', type: 'yellow_card', minute: 78, playerId: 'player-a2', teamId: 'team-ars' }, // Saliba
    ],
  },

  // ── Match 2: Liverpool 3-1 Tottenham (completed) ──────────────────────
  {
    id: 'match-2',
    homeTeamId: 'team-lfc',
    awayTeamId: 'team-thfc',
    date: '2025-01-18T17:30:00.000Z',
    status: 'completed',
    homeScore: 3,
    awayScore: 1,
    events: [
      { id: 'e2-1', type: 'penalty',     minute: 8,  playerId: 'player-l6', teamId: 'team-lfc'  }, // Salah pen
      { id: 'e2-2', type: 'yellow_card', minute: 23, playerId: 'player-t2', teamId: 'team-thfc' }, // Romero
      { id: 'e2-3', type: 'goal',        minute: 35, playerId: 'player-l8', teamId: 'team-lfc'  }, // Gakpo
      { id: 'e2-4', type: 'goal',        minute: 51, playerId: 'player-t7', teamId: 'team-thfc' }, // Son
      { id: 'e2-5', type: 'yellow_card', minute: 67, playerId: 'player-t5', teamId: 'team-thfc' }, // Bissouma
      { id: 'e2-6', type: 'goal',        minute: 74, playerId: 'player-l7', teamId: 'team-lfc'  }, // Díaz
      { id: 'e2-7', type: 'red_card',    minute: 88, playerId: 'player-t2', teamId: 'team-thfc' }, // Romero 2nd yellow
    ],
  },

  // ── Match 3: Chelsea 1-2 Liverpool (completed) ────────────────────────
  {
    id: 'match-3',
    homeTeamId: 'team-che',
    awayTeamId: 'team-lfc',
    date: '2025-02-01T15:00:00.000Z',
    status: 'completed',
    homeScore: 1,
    awayScore: 2,
    events: [
      { id: 'e3-1', type: 'goal',        minute: 14, playerId: 'player-c5', teamId: 'team-che'  }, // Palmer
      { id: 'e3-2', type: 'yellow_card', minute: 29, playerId: 'player-c6', teamId: 'team-che'  }, // Enzo
      { id: 'e3-3', type: 'goal',        minute: 42, playerId: 'player-l6', teamId: 'team-lfc'  }, // Salah
      { id: 'e3-4', type: 'yellow_card', minute: 58, playerId: 'player-c3', teamId: 'team-che'  }, // Cucurella
      { id: 'e3-5', type: 'goal',        minute: 71, playerId: 'player-l7', teamId: 'team-lfc'  }, // Díaz
      { id: 'e3-6', type: 'red_card',    minute: 83, playerId: 'player-c4', teamId: 'team-che'  }, // Caicedo
    ],
  },

  // ── Match 4: Tottenham 0-2 Arsenal (completed) ────────────────────────
  {
    id: 'match-4',
    homeTeamId: 'team-thfc',
    awayTeamId: 'team-ars',
    date: '2025-02-15T12:30:00.000Z',
    status: 'completed',
    homeScore: 0,
    awayScore: 2,
    events: [
      { id: 'e4-1', type: 'yellow_card', minute: 31, playerId: 'player-t4', teamId: 'team-thfc' }, // Porro
      { id: 'e4-2', type: 'goal',        minute: 44, playerId: 'player-a7', teamId: 'team-ars'  }, // Martinelli
      { id: 'e4-3', type: 'yellow_card', minute: 58, playerId: 'player-t5', teamId: 'team-thfc' }, // Bissouma
      { id: 'e4-4', type: 'yellow_card', minute: 68, playerId: 'player-a4', teamId: 'team-ars'  }, // Rice
      { id: 'e4-5', type: 'red_card',    minute: 73, playerId: 'player-t2', teamId: 'team-thfc' }, // Romero
      { id: 'e4-6', type: 'goal',        minute: 79, playerId: 'player-a6', teamId: 'team-ars'  }, // Saka
    ],
  },

  // ── Match 5: Arsenal 1-1 Liverpool (LIVE) ─────────────────────────────
  {
    id: 'match-5',
    homeTeamId: 'team-ars',
    awayTeamId: 'team-lfc',
    date: new Date().toISOString(),
    status: 'live',
    homeScore: 1,
    awayScore: 1,
    events: [
      { id: 'e5-1', type: 'goal',        minute: 22, playerId: 'player-a6', teamId: 'team-ars' }, // Saka
      { id: 'e5-2', type: 'yellow_card', minute: 37, playerId: 'player-l4', teamId: 'team-lfc' }, // Mac Allister
      { id: 'e5-3', type: 'goal',        minute: 55, playerId: 'player-l6', teamId: 'team-lfc' }, // Salah
    ],
  },

  // ── Match 6: Chelsea vs Tottenham (scheduled) ─────────────────────────
  {
    id: 'match-6',
    homeTeamId: 'team-che',
    awayTeamId: 'team-thfc',
    date: new Date(Date.now() + 2 * 86400000).toISOString(),
    status: 'scheduled',
    homeScore: 0,
    awayScore: 0,
    events: [],
  },
];
