import { Player, Team, Match } from './types';

export const mockTeams: Team[] = [
  {
    id: 'team-1',
    name: 'Manchester United',
    logo: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_badge.png',
    country: 'England',
    founded: 1878,
    wins: 15,
    losses: 3,
    draws: 2,
    goalsDifference: 32,
  },
  {
    id: 'team-2',
    name: 'Liverpool FC',
    logo: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
    country: 'England',
    founded: 1892,
    wins: 16,
    losses: 2,
    draws: 2,
    goalsDifference: 35,
  },
  {
    id: 'team-3',
    name: 'Manchester City',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
    country: 'England',
    founded: 1880,
    wins: 17,
    losses: 1,
    draws: 2,
    goalsDifference: 38,
  },
];

export const mockPlayers: Player[] = [
  // Manchester United Players
  {
    id: 'player-1',
    name: 'Harry Maguire',
    position: 'DEF',
    teamId: 'team-1',
    goals: 1,
    assists: 2,
    matches: 18,
    jerseyNumber: 5,
  },
  {
    id: 'player-2',
    name: 'Marcus Rashford',
    position: 'FWD',
    teamId: 'team-1',
    goals: 12,
    assists: 5,
    matches: 18,
    jerseyNumber: 10,
  },
  {
    id: 'player-3',
    name: 'David de Gea',
    position: 'GK',
    teamId: 'team-1',
    goals: 0,
    assists: 0,
    matches: 18,
    jerseyNumber: 1,
  },
  {
    id: 'player-4',
    name: 'Bruno Fernandes',
    position: 'MID',
    teamId: 'team-1',
    goals: 8,
    assists: 10,
    matches: 18,
    jerseyNumber: 8,
  },
  // Liverpool Players
  {
    id: 'player-5',
    name: 'Mohamed Salah',
    position: 'FWD',
    teamId: 'team-2',
    goals: 16,
    assists: 6,
    matches: 20,
    jerseyNumber: 11,
  },
  {
    id: 'player-6',
    name: 'Virgil van Dijk',
    position: 'DEF',
    teamId: 'team-2',
    goals: 2,
    assists: 1,
    matches: 19,
    jerseyNumber: 4,
  },
  {
    id: 'player-7',
    name: 'Alisson',
    position: 'GK',
    teamId: 'team-2',
    goals: 0,
    assists: 0,
    matches: 20,
    jerseyNumber: 1,
  },
  {
    id: 'player-8',
    name: 'Luis Diaz',
    position: 'FWD',
    teamId: 'team-2',
    goals: 10,
    assists: 4,
    matches: 18,
    jerseyNumber: 7,
  },
  // Manchester City Players
  {
    id: 'player-9',
    name: 'Erling Haaland',
    position: 'FWD',
    teamId: 'team-3',
    goals: 20,
    assists: 3,
    matches: 18,
    jerseyNumber: 9,
  },
  {
    id: 'player-10',
    name: 'Manuel Akanji',
    position: 'DEF',
    teamId: 'team-3',
    goals: 1,
    assists: 0,
    matches: 15,
    jerseyNumber: 25,
  },
  {
    id: 'player-11',
    name: 'Ederson',
    position: 'GK',
    teamId: 'team-3',
    goals: 0,
    assists: 0,
    matches: 18,
    jerseyNumber: 31,
  },
  {
    id: 'player-12',
    name: 'Kevin De Bruyne',
    position: 'MID',
    teamId: 'team-3',
    goals: 6,
    assists: 8,
    matches: 17,
    jerseyNumber: 17,
  },
];

export const mockMatches: Match[] = [
  {
    id: 'match-1',
    homeTeamId: 'team-1',
    awayTeamId: 'team-2',
    date: new Date(Date.now() + 86400000).toISOString(),
    status: 'scheduled',
    homeScore: 0,
    awayScore: 0,
  },
  {
    id: 'match-2',
    homeTeamId: 'team-3',
    awayTeamId: 'team-1',
    date: new Date().toISOString(),
    status: 'live',
    homeScore: 1,
    awayScore: 0,
  },
  {
    id: 'match-3',
    homeTeamId: 'team-2',
    awayTeamId: 'team-3',
    date: new Date(Date.now() - 86400000).toISOString(),
    status: 'completed',
    homeScore: 2,
    awayScore: 1,
  },
];
